spring:
  datasource:
    url: ${JAWSDB_URL}
    username: ${JAWSDB_USERNAME}
    password: ${JAWSDB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
server:
  port: 9000

