spring:
  datasource:
    maxActive: 3
    url: jdbc:mysql://localhost:3306/recipe_test?serverTimezone=UTC
    username: root
    password: shenailin1
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 600000
      maximumPoolSize: 4
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
application:
  jwt:
    secretKey: wbdvprojectrecipeapplicationserverailinxinyueross
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 1

